### ISSUE TITLE
Favourite recipes

### ISSUE THREAD

**Issue by Fatima101** [mdidomizio/Final-Project---Adelya-Miriam-Fatima#16]
Favorite recipes should be saved and visible in the favorites tab

**Comment by adelyanasretdinova** [comment]
- make sure  favorites recipes cards are ready

**Comment by adelyanasretdinova** [comment]
-  database for favorites are ready

**Comment by adelyanasretdinova** [comment]
- create a request from frontend to backend to store the recipe in the database

**Comment by adelyanasretdinova** [comment]
- create a response in backend to store recipe in the database

**Comment by adelyanasretdinova** [comment]
- to display items from the favorites database in frontend (favorite recipes cards)
